[package]
name = "hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redhook = { git = "https://github.com/taoky/redhook.git", rev = "b8ac9e826ab43ea30495cae255103166762e0493" }
