[package]
name = "buhao_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
log = "0.4.17"
redhook = { git = "https://github.com/taoky/redhook.git", rev = "b8ac9e826ab43ea30495cae255103166762e0493" }

[dev-dependencies]
test-log = "0.2.11"
env_logger = "0.9"
ctor = "0.2.4"
